package com.he.dao.county;

import com.he.domain.county.FrontCity;
import com.he.domain.county.FrontCityExample;
import java.util.List;
import java.util.Map;

public interface FrontCityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_city
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_city
     *
     * @mbg.generated
     */
    int insert(FrontCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_city
     *
     * @mbg.generated
     */
    int insertSelective(FrontCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_city
     *
     * @mbg.generated
     */
    List<FrontCity> selectByExample(FrontCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_city
     *
     * @mbg.generated
     */
    FrontCity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FrontCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FrontCity record);

    public abstract Map<String, Object> totalMessageOne();

    public abstract List<Map<String,Object>> totalMessageTwo();

    public abstract Map<String, Object> totalMessageThree(Long id);

    public abstract void updateById(Long cityId);
}